default: 'help'
expose: ['help','info','promote','build','release','publish']
configuration: ~/.dockerhub.yml
# ~/.dockerhub.yml should contains:
# DOCKERHUB_USER: <your dockerhub user>
# DOCKERHUB_PASS: <your dockerhub password or a dockerhub token>

properties:
  latest: false

targets:
  
  help:
    doc: 'print this message'
    steps:
    # - $: 'neon -info' => incorrect order, issue to open
    - color: 'cyan'
      print: 'Available targets'
    - print: ''
    - print: 'help     print this message'
    - print: 'info     print build informations'
    - print: 'promote  promote the project with a new tag based on git log history'
    - print: 'build    build docker images locally [will trigger: info]'
    - print: 'release  build docker images locally with tagged versions [will trigger: info->build]'
    - print: 'publish  publish docker images to Dockerhub [will trigger: info->build->release]'
    - print: ''
    - print: 'Example : neon -props "{latest: true}" promote publish'
  
  info:
    doc: 'print build informations'
    steps:
    - $: 'git describe --tags --exact-match 2>/dev/null || git symbolic-ref -q --short HEAD'
      1=: 'tag'
      3x: true
    - $: 'echo -n "={tag}" | sed -e s/^v//'
      1=: 'version'
      3x: true
    - $: 'git rev-parse HEAD 2>/dev/null'
      1=: 'commit'
      3x: true
    - 'date = now()'
    - $: 'git config user.email'
      1=: 'by'
      3x: true
    - $: 'if expr match "={version}" "\d\+\.\d\+\.\d\+" 1>/dev/null 2>&1; then echo -n "yes"; else echo -n "no"; fi'
      1=: 'is_release'
      3x: true
    - $: 'cut -f1 -d.'
      <: '=version'
      1=: 'version_major'
      3x: true
    - $: 'cut -f2 -d.'
      <: '=version'
      1=: 'version_minor'
      3x: true
    - $: 'cut -f3 -d.'
      <: '=version'
      1=: 'version_patch'
      3x: true
    - print: |-
        TAG     = ={tag}
        COMMIT  = ={commit}
        DATE    = ={date}
        BY      = ={by}
        RELEASE = ={is_release}
    - if: 'is_release == "yes"'
      then:
      - print: |-
          VERSION = ={version_major}.={version_minor}.={version_patch}
  
  promote:
    doc: 'promote the project with a new tag based on git log history'
    steps:
    - $: 'git tag $(svu next || echo -n v0.1.0)'
      2x: true
    - $: 'echo Promoted to $(svu current)'
  
  build:
    doc: 'build docker images locally'
    unless: 'newer("build/last", find(".", "Dockerfile", "**/*.sh", ".zshrc", ".p10k.zsh"))'
    depends: 'info'
    steps:
    - print: 'Executing build target'
      color: cyan
    - mkdir: 'build'
  # - $: 'sudo docker build -q -t adrienaury/go-devcontainer:={tag}-light --target go-devcontainer-light .'
    - $: 'sudo docker build -q --iidfile build/last -t adrienaury/go-devcontainer:={tag} --target go-devcontainer .'
  
  # run "neon -props '{latest: true}' release" to include latest tag
  release:
    doc: 'build docker images locally with tagged versions'
    # unless: 'is_release != "yes"' => is_release unknown variable, issue to open
    depends: ['info','build']
    steps:
    - if: 'is_release == "yes"'
      then:
    # - $: 'sudo docker tag adrienaury/go-devcontainer:={tag}-light adrienaury/go-devcontainer:v={version_major}-light'
    # - $: 'sudo docker tag adrienaury/go-devcontainer:={tag}-light adrienaury/go-devcontainer:v={version_major}.={version_minor}-light'
    # - if: 'latest'
    #   then:
    #   - $: 'sudo docker tag adrienaury/go-devcontainer:={tag}-light adrienaury/go-devcontainer:latest-light'
      - $: 'sudo docker tag adrienaury/go-devcontainer:={tag} adrienaury/go-devcontainer:v={version_major}'
      - $: 'sudo docker tag adrienaury/go-devcontainer:={tag} adrienaury/go-devcontainer:v={version_major}.={version_minor}'
      - if: 'latest'
        then:
        - $: 'sudo docker tag adrienaury/go-devcontainer:={tag} adrienaury/go-devcontainer:latest'
      - $: 'sudo docker images --no-trunc | grep $(cat build/last)'
      else:
      - print: 'Skipping release target (not a release)'
        color: red
  
  docker-login:
    steps:
    - $: 'sudo docker login -u ={DOCKERHUB_USER} -p ={DOCKERHUB_PASS}'
      2x: true
  
  # run "neon -props '{latest: true}' publish" to include latest tag
  publish:
    doc: 'push docker images to Dockerhub'
    # unless: 'is_release != "yes"' => is_release unknown variable, issue to open
    depends: ['info','release','docker-login']
    steps:
    - if: 'is_release == "yes"'
      then:
    # - $: 'sudo docker push adrienaury/go-devcontainer:={tag}-light'
    # - $: 'sudo docker push adrienaury/go-devcontainer:v={version_major}-light'
    # - $: 'sudo docker push adrienaury/go-devcontainer:v={version_major}.={version_minor}-light'
    # - if: 'latest'
    #   then:
    #   - $: 'sudo docker push adrienaury/go-devcontainer:latest-light'
      - $: 'sudo docker push adrienaury/go-devcontainer:={tag}'
      - $: 'sudo docker push adrienaury/go-devcontainer:v={version_major}'
      - $: 'sudo docker push adrienaury/go-devcontainer:v={version_major}.={version_minor}'
      - if: 'latest'
        then:
        - $: 'sudo docker push adrienaury/go-devcontainer:latest'
      else:
      - print: 'Skipping release target (not a release)'
        color: red
